### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Angus",
  "email": "angus@test.com",
  "profile_picture": "",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "angus@test.com",
  "password": "password"
}
